// <auto-generated />
namespace CodeTalk.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fixTalkClassCommentsPublic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixTalkClassCommentsPublic));
        
        string IMigrationMetadata.Id
        {
            get { return "201310140159463_fixTalkClassCommentsPublic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
